version: "3.8"

services:
    postgres:
        image: bitnami/postgresql:latest
        ports:
            - ${DATABASE_PORT-5432}:${DATABASE_PORT-5432}
        environment:
            POSTGRES_USER: ${DB_USERNAME-user}
            POSTGRES_PASSWORD: ${DB_PASSWORD-rootpass}
            POSTGRES_DB: ${DB_DATABASE-database}
            PGDATA: /data/postgres
        volumes:
            - ./data/pg:/data/postgres
        healthcheck:
            test: pg_isready
            interval: 10s
            timeout: 5s
            retries: 5

    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start:prod
        ports:
            - ${APP_PORT-3333}:${APP_PORT-3333}
