version: "3.8"

services:
    app:
        container_name: audit-log
        image: italic/audit-log:latest
        command: node src/infra/main.js --allowed_origins=${ALLOWED_ORIGINS} --color --cluster
        environment:
            - NODE_ENV=production
        restart: "on-failure"
        volumes:
            - ./data/nest:/root/.nest

        ports:
            - ${APP_PORT-3333}:${APP_PORT-3333}
        depends_on:
            - postgres
        links:
            - postgres

    postgres:
        container_name: audit-db
        image: bitnami/postgresql:latest
        ports:
            - ${DATABASE_PORT-5432}:5432
        environment:
            POSTGRES_USER: ${DB_USERNAME-user}
            POSTGRES_PASSWORD: ${DB_PASSWORD-rootpass}
            POSTGRES_DB: ${DB_DATABASE-database}
            PGDATA: /data/postgres
        volumes:
            - ./data/pg:/data/postgres
        healthcheck:
            test: pg_isready
            interval: 10s
            timeout: 5s
            retries: 5
