# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Build CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        services:
            postgres:
                image: bitnami/postgresql
                ports:
                    - 5432:5432
                env:
                    POSTGRESQL_USERNAME: docker
                    POSTGRESQL_PASSWORD: docker
                    POSTGRESQL_DATABASE: auditlog

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache pnpm modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-pnpm-modules
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            - uses: pnpm/action-setup@v2.4.0
              with:
                  version: 8.x.x
                  run_install: false
            - name: Install Dependencies
              run: |
                  pnpm i
            - name: Build project
              run: |
                  pnpm run bundle
                   npx prisma migrate dev
              env:
                  DATABASE_URL: "postgresql://docker:docker@localhost:5432/auditlog?schema=public"

            - name: Test Bundle Server
              run: |
                  bash scripts/workflows/test-server.sh
    test:
        uses: ./.github/workflows/test.yml
