name: Run Unit Tests

on: [push]

jobs:
    run-unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8

            - run: pnpm run test
