name: Run E2E Tests

on: [pull_request]

jobs:
    run-e2e-tests:
        name: Run E2E Tests
        runs-on: ubuntu-latest

        services:
            postgres:
                image: bitnami/postgresql
                ports:
                    - 5432:5432
                env:
                    POSTGRESQL_USERNAME: docker
                    POSTGRESQL_PASSWORD: docker
                    POSTGRESQL_DATABASE: auditlog

        steps:
            - uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8

            - run: pnpm i

            - run: pnpm run test:e2e
              env:
                  DATABASE_URL: "postgresql://docker:docker@localhost:5432/auditlog?schema=public"
